name: workspace
channels:
- anaconda
- defaults
- pytorch
dependencies:
- pandas=0.24.2
- python=3.7.3
- pytorch=1.1.0
- scikit-image=0.15.0
- tensorboard=1.13.1
- pip:
  - arrow==0.13.1
  - gin-config==0.1.4
  - imgaug==0.2.9
  - pylint==2.3.1
  - pytest==4.5.0
  - tensorboardX==1.6
  - tqdm==4.31.1
